### ISSUE TITLE
Spawning of notebooks should not fail if DataHub is unavailable 

### ISSUE THREAD

**Issue by andrea-manzi** [EGI-Federation/egi-notebooks-hub#75]
# Short Description of the issue

During this last week we had a couple of downtimes for DataHub upgrades ( both for Onezone and the oneprovider at CESNET which is used by Notebooks) and in both cases the EGI Notebooks was not available ( I got an error 403).

We should make sure that in case the DataHub ( Onezone or  Oneprovider) is not available users can still use the service ( maybe with a warning that DataHub is not accessible)

**Comment by enolfc** [comment]
Fixed in #76
